### ISSUE TITLE
Region / Vehicle 

### ISSUE THREAD

**Issue by rups22** [amstrdm/Bolt4Free#12]
Love the concept. 
Im in Barcelona attempting to use the script but receiving “Vehicle not in cache” errors. (Tested on the bolt e bikes with 6 digit code) 

would this be a region / vehicle issue? 

TIA

**Comment by amstrdm** [comment]
This is indeed a region issue the code would likely have to be adjusted to work with the vehicles in cache for your specific area. Bolt uses different caches for different regions so unfortunately the only way to solve this problem is to analyze the API requests sent through the Bolt app.
