### ISSUE TITLE
Vehicle not in cache

### ISSUE THREAD

**Issue by 6Mariooo** [amstrdm/Bolt4Free#2]
i got error code 10003 message vehicle not in cache
how is the cache supposed to be like?
__cf_bm=ZULjOXlazev3L9eESBeJovXFdSQOjYj.YYzkqX76URI-1687867840-0-AbxmjHgfs6Md8krmHo3VzVfJ4t8Op4MStMnIdi315qA6ytf0ecHl1Y25BP9stI3t4RfL1tNQGzNtbQRwjQRVjzE= like that?

**Comment by 6Mariooo** [comment]
and i can’t get the payment id i only have on burp suite the payment method id

**Comment by amstrdm** [comment]
The vehicle id is under the QR code of the bolt scooter you have to physically find a scooter and enter the id. What you gave in here is your authorization cookie I therefore strongly suggest you delete this question as this cookie should remain private and in combination with other factors gives access to your bolt account.

**Comment by 6Mariooo** [comment]
thats an alternate account its ok,can you help me run it?i tried with a
actual bolt id


În dum., 6 aug. 2023 la 12:20, Antonio Caserta ***@***.***> a
scris:
