### ISSUE TITLE
Vehicle not in cache

### ISSUE THREAD

**Issue by Adelinn12121** [amstrdm/Bolt4Free#4]
{"code":1003,"message":"VEHICLE_NOT_IN_CACHE"}

**Comment by amstrdm** [comment]
Can you provide additional information? It's hard to resolve the issue with just the error code. What was your input for the vehicle ID the program asks for?

**Comment by Adelinn12121** [comment]
sure,here is the console:
![image](https://github.com/amstrdm/Bolt4Free/assets/141361694/b51257bc-d354-4991-9b26-d8549c73f5af)

**Comment by Adelinn12121** [comment]
ok so i tried another scooter code and it is no more the VEHICLE_NOT_IN_CACHE,it is this:
![image](https://github.com/amstrdm/Bolt4Free/assets/141361694/eb64f9c3-add7-49b5-a1b8-c9b87996b3fe)
 do my phone has to be close to the scooter or something?

**Comment by Adelinn12121** [comment]
i tried with a scooter from a different country and it said that is too far away, however i tried 5 different scooters from romania,the place where i live,and none of that worked,still the vehicle not in cache error.do this script really work in romania?or only in somewhat country

**Comment by debatesobased** [comment]
> i tried with a scooter from a different country and it said that is too far away, however i tried 5 different scooters from romania,the place where i live,and none of that worked,still the vehicle not in cache error.do this script really work in romania?or only in somewhat country

we have other host links look it up . We dont have germany-rental-taxify
