### ISSUE TITLE
The host my app sends requests to is https://user.live.boltsvc.net. I will try to get it to work.

### ISSUE THREAD

**Issue by swiezaczek** [amstrdm/Bolt4Free#6]
Do not break the law. Everything that you read about here is for EDUCATIONAL PURPOSES just to prove its possible to accomplish it, not to get free rides!!

I managed to  get it to work, but in part only. The problem I have now after the ride is cancelled for a few times without a charge - I am being charged for next scripted rides(their status doesn't show as cancelled). Did they fix the bug or I am doing something wrong? Its worth noting I had to set sleep time higher from 0.5 to 1, otherwise I was receiving error VEHICLE_IN_WRONG_STATE_FOR_THIS_ACTION.

Any tips?

I guess it doesnt work anymore and they fixed it already by allowing few rides cancellations without a charging your card, and for next rides "if the duration of a ride is under a given timeframe there will be no charge." rule doesnt work. Am I wrong? Is there any other explanation?

**Comment by amstrdm** [comment]
Yes, that's right, it was recently fixed after I disclosed this bug to Bolt
